FROM --platform=linux/amd64 ubuntu:22.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential

COPY . /repo
WORKDIR /repo/data
RUN g++ -o ToArray ToArray.cpp

RUN mkdir -p /deps
RUN ldd /repo/data/ToArray | tr -s '[:blank:]' '\n' | grep '^/' | xargs -I % sh -c 'cp % /deps;'

FROM ubuntu:22.04 as package

COPY --from=builder /deps /deps
COPY --from=builder /repo/data/ToArray /repo/data/ToArray
ENV LD_LIBRARY_PATH=/deps
